### ISSUE TITLE
Mismacth passwords 

### ISSUE THREAD

**Issue by gelevanog** [Nightapes/ngx-validators#46] opened 2017-09-15 08:25 UTC
Form stays invalid if confirm password is filled up first before the password invalid

**Comment by Nightapes** [comment] 2018-09-09 18:45
@gelevanog  Should be fixed in the new release
Can't reproduce on https://nightapes.github.io/ngx-validators/#/password/mismatch

**Closed by Nightapes** 2018-09-09 18:45 UTC
